use_frameworks!

platform :ios, '8.0'

target 'HKNetAddtion_Example' do
  pod 'HKNetAddtion', :path => '../'

  target 'HKNetAddtion_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
